name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -r win-x64 --self-contained

    - name: Archive the build
      run: |
        mkdir -p release
        cp -R ./WinFormsApp1/bin/Release/net8.0-windows/win-x64/publish/* release/
      shell: bash

    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: WindowsFormsApp
        path: release
        compression-level: 9

    - name: Create Github Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: true
        prerelease: false
        body: |
          ## Changes
          New build of Windows Forms Application.